from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional


@dataclass(frozen=True)
class AssessmentRule:
    rule_id: str
    title: str
    target_platforms: List[str]
    condition: str
    severity: str
    category: str
    description: str
    expected: str
    recommendation: str
    cis_controls: List[str] = field(default_factory=list)
    enabled: bool = True
    metadata: Dict[str, object] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, object]:
        return asdict(self)


RULES: List[AssessmentRule] = [
    AssessmentRule(
        rule_id="RULE-WIN-001",
        title="Windows update data missing",
        target_platforms=["windows"],
        condition="missing_update_data",
        severity="medium",
        category="patching",
        description="Windows host does not include update assessment data.",
        expected="Windows host should include update assessment data.",
        recommendation="Ensure the Windows agent collects and reports update information.",
        cis_controls=["CIS Control 7"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-002",
        title="Windows security updates missing",
        target_platforms=["windows"],
        condition="missing_security_updates",
        severity="high",
        category="patching",
        description="Windows host reports missing security updates.",
        expected="Windows host should not have missing security updates.",
        recommendation="Review and apply approved security updates on the endpoint.",
        cis_controls=["CIS Control 7"],
    ),
    AssessmentRule(
        rule_id="RULE-LNX-001",
        title="Linux update data missing",
        target_platforms=["linux"],
        condition="missing_update_data",
        severity="medium",
        category="patching",
        description="Linux host does not include update assessment data.",
        expected="Linux host should include update assessment data.",
        recommendation="Ensure the Linux agent collects and reports update information.",
        cis_controls=["CIS Control 7"],
    ),
    AssessmentRule(
        rule_id="RULE-LNX-002",
        title="Linux security updates missing",
        target_platforms=["linux"],
        condition="missing_security_updates",
        severity="high",
        category="patching",
        description="Linux host reports missing security updates.",
        expected="Linux host should not have missing security updates.",
        recommendation="Review and apply approved security updates on the endpoint.",
        cis_controls=["CIS Control 7"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-001",
        title="Software inventory missing",
        target_platforms=["windows", "linux"],
        condition="missing_software_inventory",
        severity="medium",
        category="inventory",
        description="Host does not include software inventory data.",
        expected="Host should include software inventory data.",
        recommendation="Ensure the agent collects installed software or package inventory.",
        cis_controls=["CIS Control 1", "CIS Control 2"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-002",
        title="Host identity data missing",
        target_platforms=["windows", "linux"],
        condition="missing_host_identity",
        severity="high",
        category="identity",
        description="Host is missing basic identity data such as hostname, OS, or IP.",
        expected="Host should include hostname, OS, and IP information.",
        recommendation="Ensure host identity fields are collected before ingestion.",
        cis_controls=["CIS Control 1"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-003",
        title="UCKG alignment missing",
        target_platforms=["windows", "linux"],
        condition="uckg_alignment_missing",
        severity="low",
        category="alignment",
        description="Host could not be aligned to a UCKG entity.",
        expected="Host should align to a UCKG entity.",
        recommendation="Review normalized host fields and alignment logic.",
        cis_controls=["CIS Control 1"],
        enabled=False,
    ),
    AssessmentRule(
        rule_id="RULE-COM-004",
        title="Too many network interfaces",
        target_platforms=["windows", "linux"],
        condition="excessive_interface_count",
        severity="medium",
        category="network",
        description="Host has an unusually high number of interfaces or IP addresses.",
        expected="Host should have a reasonable number of interfaces.",
        recommendation="Review host network configuration and interface inventory.",
        cis_controls=["CIS Control 1"],
        metadata={"threshold": 10},
    ),
    AssessmentRule(
        rule_id="RULE-COM-005",
        title="No network interfaces detected",
        target_platforms=["windows", "linux"],
        condition="no_network_interfaces",
        severity="high",
        category="network",
        description="Host has no detected network interfaces.",
        expected="Host should have at least one network interface.",
        recommendation="Verify host network configuration and agent collection.",
        cis_controls=["CIS Control 1", "CIS Control 12"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-006",
        title="No IPv4 address detected",
        target_platforms=["windows", "linux"],
        condition="no_ipv4_address",
        severity="medium",
        category="network",
        description="Host does not have a valid IPv4 address.",
        expected="Host should have at least one IPv4 address.",
        recommendation="Verify network configuration and connectivity.",
        cis_controls=["CIS Control 12"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-007",
        title="No DNS servers configured",
        target_platforms=["windows", "linux"],
        condition="no_dns_servers",
        severity="medium",
        category="network",
        description="Host has no DNS servers configured.",
        expected="Host should have DNS servers configured.",
        recommendation="Configure valid DNS servers for the host.",
        cis_controls=["CIS Control 12"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-008",
        title="Update status incomplete",
        target_platforms=["windows", "linux"],
        condition="incomplete_update_status",
        severity="medium",
        category="patching",
        description="Update status fields are incomplete or missing key values.",
        expected="Update status should include update counts or availability.",
        recommendation="Ensure update checks provide complete patch status data.",
        cis_controls=["CIS Control 7"],
        enabled=False,
    ),
    AssessmentRule(
        rule_id="RULE-COM-009",
        title="No default gateway configured",
        target_platforms=["windows", "linux"],
        condition="no_default_gateway",
        severity="medium",
        category="network",
        description="Host does not have a default gateway configured.",
        expected="Host should have a valid default gateway.",
        recommendation="Verify network configuration and default route settings.",
        cis_controls=["CIS Control 12"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-010",
        title="No DNS servers configured",
        target_platforms=["windows", "linux"],
        condition="no_dns_servers",
        severity="medium",
        category="network",
        description="Host does not have DNS servers configured.",
        expected="Host should have one or more DNS servers configured.",
        recommendation="Configure valid DNS servers for the host.",
        cis_controls=["CIS Control 12"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-011",
        title="Discovery exposure includes SMB",
        target_platforms=["windows", "linux"],
        condition="smb_exposed_in_discovery",
        severity="medium",
        category="network",
        description="Discovery data shows SMB-related ports exposed on the host.",
        expected="SMB exposure should be reviewed and limited to approved cases.",
        recommendation="Review host exposure and restrict SMB-related services if not required.",
        cis_controls=["CIS Control 12"],
    ),
    AssessmentRule(
        rule_id="RULE-COM-012",
        title="Update status missing update counts",
        target_platforms=["windows", "linux"],
        condition="missing_update_counts",
        severity="low",
        category="patching",
        description="Update status does not report update count fields.",
        expected="Update status should report update count information.",
        recommendation="Improve update collection logic to include patch count fields.",
        cis_controls=["CIS Control 7"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-001",
        title="UAC disabled",
        target_platforms=["windows"],
        condition="uac_disabled",
        severity="medium",
        category="secure_configuration",
        description="User Account Control is disabled.",
        expected="UAC should be enabled.",
        recommendation="Enable User Account Control.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-002",
        title="Firewall disabled",
        target_platforms=["windows"],
        condition="firewall_disabled",
        severity="high",
        category="secure_configuration",
        description="One or more firewall profiles are disabled.",
        expected="All firewall profiles should be enabled.",
        recommendation="Enable Windows Firewall on all profiles.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-003",
        title="Defender realtime protection disabled",
        target_platforms=["windows"],
        condition="defender_realtime_disabled",
        severity="high",
        category="secure_configuration",
        description="Defender realtime protection is disabled.",
        expected="Realtime protection should be enabled.",
        recommendation="Enable Defender realtime protection.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-004",
        title="Guest account enabled",
        target_platforms=["windows"],
        condition="guest_account_enabled",
        severity="medium",
        category="secure_configuration",
        description="Guest account is enabled.",
        expected="Guest account should be disabled.",
        recommendation="Disable Guest account.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-005",
        title="Remote Desktop enabled",
        target_platforms=["windows"],
        condition="rdp_enabled",
        severity="medium",
        category="secure_configuration",
        description="Remote Desktop is enabled.",
        expected="RDP should be disabled unless required.",
        recommendation="Disable RDP if not required.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-006",
        title="Autorun not disabled",
        target_platforms=["windows"],
        condition="autorun_enabled",
        severity="medium",
        category="secure_configuration",
        description="Autorun is not disabled.",
        expected="Autorun should be disabled.",
        recommendation="Disable Autorun.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-007",
        title="No inactivity timeout configured",
        target_platforms=["windows"],
        condition="no_inactivity_timeout",
        severity="low",
        category="secure_configuration",
        description="No inactivity timeout is configured.",
        expected="Inactivity timeout should be configured.",
        recommendation="Set session timeout to 15 minutes or less.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-008",
        title="Weak inactivity timeout",
        target_platforms=["windows"],
        condition="weak_inactivity_timeout",
        severity="low",
        category="secure_configuration",
        description="Inactivity timeout is too long.",
        expected="Timeout should be 900 seconds or less.",
        recommendation="Reduce inactivity timeout.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-009",
        title="Password complexity disabled",
        target_platforms=["windows"],
        condition="password_complexity_disabled",
        severity="medium",
        category="secure_configuration",
        description="Password complexity is disabled.",
        expected="Password complexity should be enabled.",
        recommendation="Enable password complexity.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-010",
        title="Weak password length",
        target_platforms=["windows"],
        condition="weak_password_length",
        severity="medium",
        category="secure_configuration",
        description="Password length is below recommended minimum.",
        expected="Minimum password length should be 14 or greater.",
        recommendation="Increase minimum password length.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-011",
        title="Weak password history",
        target_platforms=["windows"],
        condition="weak_password_history",
        severity="low",
        category="secure_configuration",
        description="Password history is too short.",
        expected="Password history should be 24 or greater.",
        recommendation="Increase password history length.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
        rule_id="RULE-WIN-C4-012",
        title="Weak lockout threshold",
        target_platforms=["windows"],
        condition="weak_lockout_threshold",
        severity="medium",
        category="secure_configuration",
        description="Lockout threshold is not securely configured.",
        expected="Lockout threshold should be 10 or fewer invalid attempts.",
        recommendation="Set lockout threshold to 10 or fewer invalid attempts.",
        cis_controls=["CIS Control 4"],
    ),
    AssessmentRule(
    rule_id="RULE-WIN-C4-013",
    title="Password policy data missing",
    target_platforms=["windows"],
    condition="missing_password_policy",
    severity="low",
    category="secure_configuration",
    description="Password policy data could not be collected.",
    expected="Password policy should be collected.",
    recommendation="Verify agent permissions and collection logic.",
    cis_controls=["CIS Control 4"],
),

AssessmentRule(
    rule_id="RULE-WIN-C4-014",
    title="Password complexity data missing",
    target_platforms=["windows"],
    condition="missing_password_complexity",
    severity="low",
    category="secure_configuration",
    description="Password complexity setting could not be determined.",
    expected="Password complexity should be known.",
    recommendation="Fix security policy collection method.",
    cis_controls=["CIS Control 4"],
),

AssessmentRule(
    rule_id="RULE-WIN-C4-015",
    title="Autorun configuration missing",
    target_platforms=["windows"],
    condition="missing_autorun_config",
    severity="low",
    category="secure_configuration",
    description="Autorun configuration could not be determined.",
    expected="Autorun state should be known.",
    recommendation="Ensure registry keys are accessible.",
    cis_controls=["CIS Control 4"],
),
AssessmentRule(
    rule_id="RULE-WIN-C5-001",
    title="Guest account present",
    target_platforms=["windows"],
    condition="guest_account_present",
    severity="medium",
    category="account_management",
    description="Guest account exists on system.",
    expected="Guest account should not exist.",
    recommendation="Remove or disable Guest account.",
    cis_controls=["CIS Control 5"],
),

AssessmentRule(
    rule_id="RULE-WIN-C5-002",
    title="Multiple admin accounts",
    target_platforms=["windows"],
    condition="multiple_admin_accounts",
    severity="medium",
    category="account_management",
    description="Too many administrator accounts.",
    expected="Limit number of admin accounts.",
    recommendation="Reduce admin accounts.",
    cis_controls=["CIS Control 5"],
),

AssessmentRule(
    rule_id="RULE-WIN-C5-003",
    title="Password never expires",
    target_platforms=["windows"],
    condition="password_never_expires",
    severity="high",
    category="account_management",
    description="Accounts have passwords that never expire.",
    expected="Passwords should expire.",
    recommendation="Enforce password expiration policy.",
    cis_controls=["CIS Control 5"],
),

AssessmentRule(
    rule_id="RULE-WIN-C5-004",
    title="Disabled accounts present",
    target_platforms=["windows"],
    condition="disabled_accounts_present",
    severity="low",
    category="account_management",
    description="Disabled accounts detected.",
    expected="Unused accounts should be removed.",
    recommendation="Review and remove inactive accounts.",
    cis_controls=["CIS Control 5"],
),
AssessmentRule(
    rule_id="RULE-WIN-C6-001",
    title="Admin accounts present",
    target_platforms=["windows"],
    condition="admin_accounts_exist",
    severity="low",
    category="access_control",
    description="Administrative accounts detected.",
    expected="Admin accounts should be limited.",
    recommendation="Review necessity of admin accounts.",
    cis_controls=["CIS Control 6"],
),

AssessmentRule(
    rule_id="RULE-WIN-C6-002",
    title="Too many admin accounts",
    target_platforms=["windows"],
    condition="too_many_admins",
    severity="medium",
    category="access_control",
    description="Too many administrative accounts.",
    expected="Minimal admin accounts should exist.",
    recommendation="Reduce number of admin users.",
    cis_controls=["CIS Control 6"],
),

AssessmentRule(
    rule_id="RULE-WIN-C6-003",
    title="Admin account without password expiration",
    target_platforms=["windows"],
    condition="admin_account_without_password_expiry",
    severity="high",
    category="access_control",
    description="Admin account password does not expire.",
    expected="Admin passwords should expire.",
    recommendation="Enforce password expiration.",
    cis_controls=["CIS Control 6"],
),
AssessmentRule(
    rule_id="RULE-WIN-C8-001",
    title="Audit logging not configured",
    target_platforms=["windows"],
    condition="audit_logging_not_configured",
    severity="high",
    category="audit_logging",
    description="Audit logging is not configured.",
    expected="Audit logging should be enabled.",
    recommendation="Enable audit policy logging.",
    cis_controls=["CIS Control 8"],
),

AssessmentRule(
    rule_id="RULE-WIN-C8-002",
    title="No logon auditing",
    target_platforms=["windows"],
    condition="no_logon_auditing",
    severity="medium",
    category="audit_logging",
    description="Logon auditing is not configured.",
    expected="Logon auditing should be enabled.",
    recommendation="Enable logon audit policy.",
    cis_controls=["CIS Control 8"],
),
AssessmentRule(
    rule_id="RULE-COM-C9-001",
    title="Web browsers installed (exposure risk)",
    target_platforms=["windows"],
    condition="risky_software_installed",
    severity="low",
    category="application_security",
    description="Web browsers present potential exposure surface.",
    expected="Browser usage should be controlled and hardened.",
    recommendation="Ensure browsers are patched and configured securely.",
    cis_controls=["CIS Control 9"],
),
AssessmentRule(
    rule_id="RULE-WIN-C10-001",
    title="Antivirus disabled",
    target_platforms=["windows"],
    condition="defender_disabled",
    severity="high",
    category="malware_defense",
    description="Antivirus is disabled.",
    expected="Antivirus should be enabled.",
    recommendation="Enable Microsoft Defender or equivalent AV.",
    cis_controls=["CIS Control 10"],
),

AssessmentRule(
    rule_id="RULE-WIN-C10-002",
    title="Realtime protection disabled",
    target_platforms=["windows"],
    condition="realtime_protection_disabled",
    severity="high",
    category="malware_defense",
    description="Realtime protection is disabled.",
    expected="Realtime protection should be enabled.",
    recommendation="Enable realtime protection.",
    cis_controls=["CIS Control 10"],
),

AssessmentRule(
    rule_id="RULE-WIN-C10-003",
    title="Antispyware disabled",
    target_platforms=["windows"],
    condition="antispyware_disabled",
    severity="medium",
    category="malware_defense",
    description="Antispyware is disabled.",
    expected="Antispyware should be enabled.",
    recommendation="Enable antispyware protection.",
    cis_controls=["CIS Control 10"],
),
AssessmentRule(
    rule_id="RULE-WIN-C11-001",
    title="No backups detected",
    target_platforms=["windows"],
    condition="no_backups_detected",
    severity="high",
    category="data_recovery",
    description="No system backups detected.",
    expected="Backups should exist.",
    recommendation="Enable system backups or shadow copies.",
    cis_controls=["CIS Control 11"],
),
AssessmentRule(
    rule_id="RULE-COM-C13-001",
    title="No network visibility",
    target_platforms=["windows"],
    condition="no_multiple_interfaces",
    severity="low",
    category="network_monitoring",
    description="Limited network visibility detected.",
    expected="Network interfaces should be visible.",
    recommendation="Ensure network monitoring coverage.",
    cis_controls=["CIS Control 13"],
),
AssessmentRule(
    rule_id="RULE-COM-C14-001",
    title="No security tooling detected",
    target_platforms=["windows"],
    condition="no_security_tools_detected",
    severity="medium",
    category="security_awareness",
    description="No visible security tooling detected.",
    expected="Security tools should be present.",
    recommendation="Install endpoint protection and awareness tools.",
    cis_controls=["CIS Control 14"],
),
AssessmentRule(
    rule_id="RULE-COM-C15-001",
    title="Third-party software present",
    target_platforms=["windows"],
    condition="third_party_software_present",
    severity="low",
    category="vendor_management",
    description="Third-party software detected.",
    expected="Third-party software should be reviewed.",
    recommendation="Validate trusted vendors.",
    cis_controls=["CIS Control 15"],
),
AssessmentRule(
    rule_id="RULE-COM-C16-001",
    title="Large software footprint",
    target_platforms=["windows"],
    condition="many_installed_applications",
    severity="low",
    category="application_security",
    description="Large number of installed applications.",
    expected="Limit installed software.",
    recommendation="Remove unnecessary applications.",
    cis_controls=["CIS Control 16"],
),

AssessmentRule(
    rule_id="RULE-COM-C16-002",
    title="Developer tools installed",
    target_platforms=["windows"],
    condition="developer_tools_installed",
    severity="low",
    category="application_security",
    description="Developer tools increase attack surface.",
    expected="Restrict development tools.",
    recommendation="Limit to required systems.",
    cis_controls=["CIS Control 16"],
),
AssessmentRule(
    rule_id="RULE-COM-C17-001",
    title="Insufficient audit coverage",
    target_platforms=["windows"],
    condition="insufficient_audit_events",
    severity="medium",
    category="incident_response",
    description="Limited audit policy coverage.",
    expected="Comprehensive logging.",
    recommendation="Expand audit logging.",
    cis_controls=["CIS Control 17"],
),

AssessmentRule(
    rule_id="RULE-COM-C17-002",
    title="Weak incident recovery capability",
    target_platforms=["windows"],
    condition="no_backup_and_logs",
    severity="high",
    category="incident_response",
    description="Missing backups or logs.",
    expected="Backups and logs required.",
    recommendation="Enable backups and logging.",
    cis_controls=["CIS Control 17"],
),
AssessmentRule(
    rule_id="RULE-COM-C18-001",
    title="High vulnerability density",
    target_platforms=["windows"],
    condition="high_vulnerability_density",
    severity="high",
    category="penetration_testing",
    description="System shows high number of findings.",
    expected="Lower vulnerability count.",
    recommendation="Conduct penetration testing and remediation.",
    cis_controls=["CIS Control 18"],
),
]


def get_all_rules(enabled_only: bool = True) -> List[AssessmentRule]:
    if enabled_only:
        return [rule for rule in RULES if rule.enabled]
    return list(RULES)


def get_rules_for_platform(platform: str, enabled_only: bool = True) -> List[AssessmentRule]:
    normalized_platform = (platform or "").strip().lower()
    rules = get_all_rules(enabled_only=enabled_only)

    if "windows" in normalized_platform:
        platform_family = "windows"
    elif (
        "linux" in normalized_platform
        or "ubuntu" in normalized_platform
        or "debian" in normalized_platform
        or "centos" in normalized_platform
        or "rhel" in normalized_platform
        or "fedora" in normalized_platform
    ):
        platform_family = "linux"
    else:
        platform_family = normalized_platform

    return [
        rule for rule in rules
        if platform_family in [p.lower() for p in rule.target_platforms]
    ]


def get_rule_by_id(rule_id: str) -> Optional[AssessmentRule]:
    if not rule_id:
        return None

    normalized_rule_id = rule_id.strip().upper()
    for rule in RULES:
        if rule.rule_id.upper() == normalized_rule_id:
            return rule
    return None


def get_rules_as_dicts(enabled_only: bool = True) -> List[Dict[str, object]]:
    return [rule.to_dict() for rule in get_all_rules(enabled_only=enabled_only)]