from pathlib import Path
import sys

import streamlit as st

st.set_page_config(page_title="Findings", page_icon="🚨", layout="wide")

GUI_DIR = Path(__file__).resolve().parents[1]
if str(GUI_DIR) not in sys.path:
    sys.path.append(str(GUI_DIR))

from services.nav import render_sidebar
from services.data_loader import (
    load_hosts_df_from_consolidated,
    load_latest_assessment_summary_payload,
    load_latest_findings_df,
)
from services.report_service import build_system_pdf_report

render_sidebar()

st.title("Findings")
st.caption("Filter and review CIS-mapped findings generated by the collector pipeline.")

top_bar = st.container(border=True)
with top_bar:
    left, right = st.columns([1, 4])

    with left:
        if st.button("Refresh", use_container_width=True):
            st.rerun()

    with right:
        st.info("Filter findings by severity, host, category, or CIS Control.", icon="ℹ️")

findings_df, findings_path = load_latest_findings_df()
hosts_df, hosts_path = load_hosts_df_from_consolidated()
assessment_summary, summary_path = load_latest_assessment_summary_payload()

if findings_df.empty:
    st.warning("No findings dataset found.")
    st.stop()

severity_options = (
    sorted(findings_df["severity"].dropna().astype(str).unique().tolist())
    if "severity" in findings_df.columns
    else []
)
host_options = (
    sorted(findings_df["hostname"].dropna().astype(str).unique().tolist())
    if "hostname" in findings_df.columns
    else []
)
category_options = (
    sorted(findings_df["category"].dropna().astype(str).unique().tolist())
    if "category" in findings_df.columns
    else []
)
cis_options = (
    sorted(findings_df["cis_controls"].dropna().astype(str).unique().tolist())
    if "cis_controls" in findings_df.columns
    else []
)

overview_box = st.container(border=True)
with overview_box:
    st.subheader("Overview")

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Findings", len(findings_df))
    m2.metric("Hosts", len(host_options))
    m3.metric("Categories", len(category_options))
    m4.metric("CIS Mappings", len(cis_options))

report_box = st.container(border=True)
with report_box:
    left, right = st.columns([3, 1])

    with left:
        st.subheader("Export System Report")
        st.caption("Generate a PDF report covering all hosts and all findings in the latest assessment.")

    with right:
        try:
            pdf_bytes = build_system_pdf_report(
                findings_df=findings_df,
                hosts_df=hosts_df,
                assessment_summary=assessment_summary,
            )

            st.download_button(
                label="Download PDF",
                data=pdf_bytes,
                file_name="sage_ch_system_assessment_report.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        except Exception as exc:
            st.warning(str(exc))

filters_box = st.container(border=True)
with filters_box:
    st.subheader("Filters")

    f1, f2, f3, f4 = st.columns(4)
    with f1:
        selected_severity = st.multiselect("Severity", severity_options, default=severity_options)
    with f2:
        selected_hosts = st.multiselect("Host", host_options)
    with f3:
        selected_categories = st.multiselect("Category", category_options)
    with f4:
        selected_cis = st.multiselect("CIS Control", cis_options)

filtered_df = findings_df.copy()

if selected_severity and "severity" in filtered_df.columns:
    filtered_df = filtered_df[filtered_df["severity"].astype(str).isin(selected_severity)]

if selected_hosts and "hostname" in filtered_df.columns:
    filtered_df = filtered_df[filtered_df["hostname"].astype(str).isin(selected_hosts)]

if selected_categories and "category" in filtered_df.columns:
    filtered_df = filtered_df[filtered_df["category"].astype(str).isin(selected_categories)]

if selected_cis and "cis_controls" in filtered_df.columns:
    filtered_df = filtered_df[filtered_df["cis_controls"].astype(str).isin(selected_cis)]

summary_box = st.container(border=True)
with summary_box:
    st.subheader("Filtered Summary")

    s1, s2, s3 = st.columns(3)
    s1.metric("Filtered Findings", len(filtered_df))
    s2.metric("Affected Hosts", filtered_df["hostname"].nunique() if "hostname" in filtered_df.columns else 0)
    s3.metric("Categories", filtered_df["category"].nunique() if "category" in filtered_df.columns else 0)

table_box = st.container(border=True)
with table_box:
    st.subheader("Findings Table")

    display_cols = [
        c
        for c in [
            "hostname",
            "ip_address",
            "title",
            "severity",
            "category",
            "cis_controls",
            "status",
            "recommendation",
        ]
        if c in filtered_df.columns
    ]

    st.dataframe(filtered_df[display_cols], use_container_width=True, hide_index=True)

footer_box = st.container(border=True)
with footer_box:
    st.subheader("Data Sources")
    st.markdown(f"**Findings source**  \n`{findings_path}`")
    st.markdown(f"**Hosts source**  \n`{hosts_path}`")
    st.markdown(f"**Assessment summary**  \n`{summary_path if summary_path else 'Not found'}`")