from pathlib import Path
import sys

import streamlit as st

st.set_page_config(page_title="Findings", page_icon="🚨", layout="wide")

GUI_DIR = Path(__file__).resolve().parents[1]
if str(GUI_DIR) not in sys.path:
    sys.path.append(str(GUI_DIR))

from services.nav import render_sidebar
from services.data_loader import load_latest_findings_df

render_sidebar()

st.title("Findings")
st.caption("Filter and review the latest findings generated by the collector pipeline.")

top_bar = st.container(border=True)
with top_bar:
    left, right = st.columns([1, 4])

    with left:
        if st.button("Refresh", use_container_width=True):
            st.rerun()

    with right:
        st.info(
            "Use filters to narrow findings by severity, host, and category.",
            icon="ℹ️",
        )

findings_df, findings_path = load_latest_findings_df()

if findings_df.empty:
    st.warning("No findings dataset found.")
    st.stop()

severity_options = sorted([x for x in findings_df["severity"].dropna().astype(str).unique().tolist() if x]) if "severity" in findings_df.columns else []
host_options = sorted([x for x in findings_df["hostname"].dropna().astype(str).unique().tolist() if x]) if "hostname" in findings_df.columns else []
category_options = sorted([x for x in findings_df["category"].dropna().astype(str).unique().tolist() if x]) if "category" in findings_df.columns else []

overview_box = st.container(border=True)
with overview_box:
    st.subheader("Overview")

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Findings", len(findings_df))
    m2.metric("Hosts", len(host_options))
    m3.metric("Severities", len(severity_options))
    m4.metric("Categories", len(category_options))

filters_box = st.container(border=True)
with filters_box:
    st.subheader("Filters")

    f1, f2, f3 = st.columns(3)
    with f1:
        selected_severity = st.multiselect("Severity", severity_options, default=severity_options)
    with f2:
        selected_hosts = st.multiselect("Hostname", host_options)
    with f3:
        selected_categories = st.multiselect("Category", category_options)

filtered_df = findings_df.copy()

if selected_severity:
    filtered_df = filtered_df[filtered_df["severity"].astype(str).isin(selected_severity)]

if selected_hosts:
    filtered_df = filtered_df[filtered_df["hostname"].astype(str).isin(selected_hosts)]

if selected_categories:
    filtered_df = filtered_df[filtered_df["category"].astype(str).isin(selected_categories)]

summary_box = st.container(border=True)
with summary_box:
    st.subheader("Filtered Summary")

    s1, s2, s3 = st.columns(3)
    s1.metric("Filtered Findings", len(filtered_df))
    s2.metric("Filtered Hosts", filtered_df["hostname"].nunique() if "hostname" in filtered_df.columns else 0)
    s3.metric("Filtered Categories", filtered_df["category"].nunique() if "category" in filtered_df.columns else 0)

table_box = st.container(border=True)
with table_box:
    st.subheader("Findings Table")

    display_cols = [
        c for c in [
            "finding_id",
            "hostname",
            "ip_address",
            "title",
            "severity",
            "category",
            "status",
            "recommendation",
            "cis_controls",
        ]
        if c in filtered_df.columns
    ]

    st.dataframe(filtered_df[display_cols], use_container_width=True, hide_index=True)

footer_box = st.container(border=True)
with footer_box:
    st.subheader("Data Source")
    st.markdown(f"**Findings source**  \n`{findings_path}`")