from pathlib import Path
import sys

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Batches", page_icon="🗂️", layout="wide")

GUI_DIR = Path(__file__).resolve().parents[1]
if str(GUI_DIR) not in sys.path:
    sys.path.append(str(GUI_DIR))

from services.nav import render_sidebar
from services.action_service import get_latest_output_summary, get_recent_output_files_df

render_sidebar()

st.title("Batches")
st.caption("Review recent batch artifacts and output files generated by the collector pipeline.")

top_bar = st.container(border=True)
with top_bar:
    left, right = st.columns([1, 4])

    with left:
        if st.button("Refresh", use_container_width=True):
            st.rerun()

    with right:
        st.info(
            "This page shows recent output artifacts and the latest batch summary.",
            icon="ℹ️",
        )

latest_output = get_latest_output_summary()
recent_outputs_df = get_recent_output_files_df(limit=50)

overview_box = st.container(border=True)
with overview_box:
    st.subheader("Overview")

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Latest Batch", latest_output.get("batch_id") or "N/A")
    m2.metric("Total Hosts", latest_output.get("total_hosts") if latest_output.get("total_hosts") is not None else "N/A")
    m3.metric("Total Findings", latest_output.get("total_findings") if latest_output.get("total_findings") is not None else "N/A")
    m4.metric("Recent Output Files", len(recent_outputs_df) if not recent_outputs_df.empty else 0)

main_left, main_right = st.columns([1.2, 0.9])

with main_left:
    files_box = st.container(border=True)
    with files_box:
        st.subheader("Recent Output Files")

        if recent_outputs_df.empty:
            st.info("No output files found.")
        else:
            st.dataframe(recent_outputs_df, use_container_width=True, hide_index=True)

with main_right:
    summary_box = st.container(border=True)
    with summary_box:
        st.subheader("Latest Batch Summary")

        st.markdown(f"**Batch ID**  \n`{latest_output.get('batch_id') or 'N/A'}`")
        st.markdown(f"**Consolidated dataset**  \n`{latest_output.get('consolidated_path') or 'Not found'}`")
        st.markdown(f"**Findings dataset**  \n`{latest_output.get('findings_path') or 'Not found'}`")
        st.markdown(f"**Assessment summary**  \n`{latest_output.get('assessment_summary_path') or 'Not found'}`")

        st.divider()

        st.write(f"**Total hosts:** `{latest_output.get('total_hosts') if latest_output.get('total_hosts') is not None else 'N/A'}`")
        st.write(f"**Total findings:** `{latest_output.get('total_findings') if latest_output.get('total_findings') is not None else 'N/A'}`")
        st.write(f"**Findings rows loaded:** `{latest_output.get('findings_rows', 0)}`")
        st.write(f"**Graph persistence:** `{latest_output.get('graph_persistence_status') or 'N/A'}`")

        severity_counts = latest_output.get("severity_counts", {})
        if severity_counts:
            st.markdown("#### Severity Counts")
            s1, s2 = st.columns(2)
            s3, s4 = st.columns(2)
            s1.metric("Critical", severity_counts.get("critical", 0))
            s2.metric("High", severity_counts.get("high", 0))
            s3.metric("Medium", severity_counts.get("medium", 0))
            s4.metric("Low", severity_counts.get("low", 0))

        graph_persistence = latest_output.get("graph_persistence", {})
        if isinstance(graph_persistence, dict):
            error = graph_persistence.get("error", "")
            if error:
                with st.expander("Graph persistence details"):
                    st.code(str(error))